# backend/src/api/auth.py
from __future__ import annotations
from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import Session, select
from src.models.base import User
from src.db import get_session
import src.middleware.auth
from pydantic import BaseModel
from datetime import datetime
from sqlmodel.ext.asyncio.session import AsyncSession

router = APIRouter()

class UserCreate(BaseModel):
    email: str
    password: str
    name: str | None = None

@router.post("/register", response_model=User)
async def register_user(user_data: UserCreate, session: AsyncSession = Depends(get_session)):
    # This is a placeholder for actual user registration with password hashing
    # In a real app, use a library like passlib for password hashing
    
    # Check if user already exists
    result = await session.exec(select(User).where(User.email == user_data.email))
    existing_user = result.first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Email already registered")

    # In a real scenario, the user_id would be generated by the auth provider.
    # For now, we'll use a placeholder.
    # The actual integration with Better Auth will handle this.
    user_id = f"local|{user_data.email}"

    new_user = User(
        user_id=user_id,
        email=user_data.email,
        name=user_data.name
    )
    
    session.add(new_user)
    await session.commit()
    await session.refresh(new_user)
    
    # This endpoint would typically return a JWT token upon successful registration
    # That logic is in the login endpoint
    return new_user

class UserLogin(BaseModel):
    email: str
    password: str

class Token(BaseModel):
    access_token: str
    token_type: str

@router.post("/login", response_model=Token)
async def login_for_access_token(form_data: UserLogin, session: AsyncSession = Depends(get_session)):
    # This is a placeholder for actual user authentication.
    # In a real app, you would verify the password hash.
    result = await session.exec(select(User).where(User.email == form_data.email))
    user = result.first()
    if not user:
        raise HTTPException(
            status_code=401,
            detail="Incorrect email or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    # This is where password verification would happen.
    # For now, we are skipping it.
    
    # Create JWT token
    from src.middleware.auth import SECRET_KEY, ALGORITHM
    from jose import jwt
    from datetime import datetime, timedelta

    access_token_expires = timedelta(minutes=30)
    to_encode = {
        "sub": user.user_id,
        "exp": datetime.utcnow() + access_token_expires,
        "email": user.email
    }
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    
    return {"access_token": encoded_jwt, "token_type": "bearer"}

@router.get("/me", response_model=User)
async def get_me(
    session: AsyncSession = Depends(get_session),
    current_user: User = Depends(src.middleware.auth.get_current_user)
):
    result = await session.exec(select(User).where(User.user_id == current_user.user_id))
    user = result.first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return user

class UserUpdate(BaseModel):
    name: Optional[str] = None

@router.patch("/me", response_model=User)
async def update_me(
    user_update: UserUpdate,
    session: AsyncSession = Depends(get_session),
    current_user: User = Depends(src.middleware.auth.get_current_user)
):
    result = await session.exec(select(User).where(User.user_id == current_user.user_id))
    user = result.first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    
    if user_update.name is not None:
        user.name = user_update.name
    
    user.updated_at = datetime.utcnow()
    
    session.add(user)
    await session.commit()
    await session.refresh(user)
    return user
